export const strings = {
    Precipitation: "Precipitaciones (mm)",
    Temp_Air: "Temperatura (°C)",
    Temp_Air_Mean: "Temperatura (°C)",
    Temp_Air_Min: "Temperatura Mínima (°C)",
    Temp_Air_Max: "Temperatura Máxima (°C)",
    Dew_Temp: "Punto de Rocío (°C)",
    Dew_Temp_Mean: "Punto de Rocío (°C)",
    Dew_Temp_Max: "Punto de Rocío Mínima (°C)",
    Dew_Temp_Min: "Punto de Rocío Máxima (°C)",
    Relat_Hum: "Humedad Relativa (%)",
    Relat_Hum_Mean: "Humedad Relativa (%)",
    Relat_Hum_Min: "Humedad Relativa Mínima (%)",
    Relat_Hum_Max: "Humedad Relativa Máxima (%)",
    Wind_Speed: "Velocidad del viento (km/h)",
    Wind_Speed_Mean: "Velocidad del viento (km/h)",
    Wind_Speed_Min: "Velocidad del viento Mínima (km/h)",
    Wind_Speed_Max: "Velocidad del viento Máxima (km/h)",
    Atmospheric_Pressure: "Presión Atmosférica (hPa)",
    Atmospheric_Pressure_Max: "Presión Atmosférica Mínima (hPa)",
    Atmospheric_Pressure_Min: "Presión Atmosférica Máxima (hPa)",
    min: "Mínimo",
    max: "Máximo",
    mean: "Promedio",
    value: "Promedio",
}

export const abbreviations = {
    Precipitation: "lluvias (mm)",
    Temp_Air: "Temperatura (°C)",
    Temp_Air_Mean: "Temperatura (°C)",
    Temp_Air_Min: "Temp. Min. (°C)",
    Temp_Air_Max: "Temp. Máx. (°C)",
    Dew_Temp: "Punto Rocío (°C)",
    Dew_Temp_Mean: "Punto Rocío (°C)",
    Dew_Temp_Max: "Punto Rocío Min. (°C)",
    Dew_Temp_Min: "Punto Rocío Máx. (°C)",
    Relat_Hum: "Humedad Rel. (%)",
    Relat_Hum_Mean: "Humedad Rel. (%)",
    Relat_Hum_Min: "Humedad Rel. (%)",
    Relat_Hum_Max: "Humedad Rel. (%)",
    Wind_Speed: "Velocidad viento (km/h)",
    Wind_Speed_Mean: "Vel. viento (km/h)",
    Wind_Speed_Min: "Vel. viento Min. (km/h)",
    Wind_Speed_Max: "Vel. viento Máx. (km/h)",
    Atmospheric_Pressure: "Presión Atm. (hPa)",
    Atmospheric_Pressure_Max: "Presión Atm. Min. (hPa)",
    Atmospheric_Pressure_Min: "Presión Atm. Máx. (hPa)",
    min: "Mín.",
    max: "Máx.",
    mean: "Prom.",
    value: "Prom.",
}

