export const Endpoints = {
  BaseURL: process.env.REACT_APP_API_BASE_URL || process.env.API_BASE_URL,
  Api: "/api",
  login: "/auth/login/",
  register: "/auth/register/",
  Token: "/auth/refresh/",
  perfil: "/auth/porfile/",
  lotes: "/lotes/",
  áreas: "/areas/",
  enfermedad: "/enfermedades/",
  Poligonos: "/geolotes/",
  Lectura: "/lecturas/",
  Plantas: "/plantas/",
  WeatherData:'/weather/data/',
  ImportUsers:'/auth/register/import',
  Users:'/auth/users',
  Roles:'/auth/roles',
  Produccion: "/produccion/",
  Upload:"upload",
  Permissions:"/auth/permissions"
};
